import {
  Unit,
  Weapon,
  SpiritCommand,
  SpiritType,
  TerrainType,
  TerrainInfo,
} from './types';

// 地形マスターデータ
export const TERRAIN_DATA: Record<TerrainType, TerrainInfo> = {
  plain: {
    type: 'plain',
    name: '平地',
    defenseMod: 0,
    evadeMod: 0,
    moveCost: { ground: 1, flight: 1 },
    color: '#334155',
  },
  forest: {
    type: 'forest',
    name: '森林',
    defenseMod: 0.1,
    evadeMod: 0.1,
    moveCost: { ground: 2, flight: 1 },
    color: '#166534',
  },
  mountain: {
    type: 'mountain',
    name: '山岳',
    defenseMod: 0.2,
    evadeMod: 0.2,
    moveCost: { ground: 3, flight: 1 },
    color: '#713f12',
  },
  base: {
    type: 'base',
    name: '防衛基地',
    defenseMod: 0.2,
    evadeMod: 0.15,
    moveCost: { ground: 1, flight: 1 },
    healRate: 0.2, // ターン開始時HP/EN20%回復
    color: '#1e3a8a',
  },
  sea: {
    type: 'sea',
    name: '水域',
    defenseMod: -0.1,
    evadeMod: -0.1,
    moveCost: { ground: 3, flight: 1 },
    color: '#0369a1',
  },
};

// 精神コマンドマスターデータ
export const SPIRIT_COMMANDS: Record<SpiritType, SpiritCommand> = {
  hotBlood: {
    id: 'hotBlood',
    name: '熱血',
    spCost: 35,
    description: '次に行う攻撃の与ダメージが2.0倍になる。',
    icon: '🔥',
  },
  flash: {
    id: 'flash',
    name: 'ひらめき',
    spCost: 15,
    description: '1回だけ敵からの攻撃を100%回避する。',
    icon: '⚡',
  },
  sureHit: {
    id: 'sureHit',
    name: '必中',
    spCost: 20,
    description: '1ターンの間、攻撃の命中率が100%になる。',
    icon: '🎯',
  },
  ironWall: {
    id: 'ironWall',
    name: '鉄壁',
    spCost: 25,
    description: '1ターンの間、受けるダメージが1/4に激減する。',
    icon: '🛡️',
  },
  focus: {
    id: 'focus',
    name: '集中',
    spCost: 15,
    description: '1ターンの間、自機の最終命中率・回避率が+30%される。',
    icon: '👁️',
  },
  accel: {
    id: 'accel',
    name: '加速',
    spCost: 10,
    description: '1度だけ移動力が+3マス増加する。',
    icon: '👟',
  },
  guts: {
    id: 'guts',
    name: '根性',
    spCost: 20,
    description: '自機のHPを最大値の35%回復する。',
    icon: '❤️',
  },
  greatGuts: {
    id: 'greatGuts',
    name: 'ド根性',
    spCost: 40,
    description: '自機のHPを全回復する。',
    icon: '💖',
  },
  moraleUp: {
    id: 'moraleUp',
    name: '気合',
    spCost: 25,
    description: '自機の気力を+10上昇させる。',
    icon: '💥',
  },
  fortune: {
    id: 'fortune',
    name: '幸運',
    spCost: 30,
    description: '次回敵を撃破した際の獲得資金が2倍になる。',
    icon: '💰',
  },
  cheer: {
    id: 'cheer',
    name: '応援',
    spCost: 25,
    description: '指定した味方の次回獲得EXPが2倍になる。',
    icon: '📣',
  },
  bless: {
    id: 'bless',
    name: '祝福',
    spCost: 35,
    description: '指定した味方の次回撃破時資金が2倍になる。',
    icon: '✨',
  },
  trust: {
    id: 'trust',
    name: '信頼',
    spCost: 25,
    description: '指定した味方のHPを2500回復する。',
    icon: '🤝',
  },
};

// 改造コスト計算テーブル
export const UPGRADE_COSTS = [1000, 2000, 3500, 5500, 8000, 11000, 15000, 20000, 26000, 35000];

// 味方マスター機体テンプレート
export const PLAYER_UNITS_MASTER: Record<string, Omit<Unit, 'x' | 'y' | 'hasMoved' | 'hasActed' | 'activeBuffs'>> = {
  kaiser: {
    id: 'kaiser',
    mechName: 'ダイナミック・カイザー',
    faction: 'player',
    icon: '🤖',
    themeColor: '#ef4444',
    baseHp: 6500,
    baseEn: 180,
    baseArmor: 1400,
    baseMobility: 85,
    baseMove: 5,
    upgrades: { hp: 0, en: 0, armor: 0, mobility: 0, weapons: 0 },
    hp: 6500,
    maxHp: 6500,
    en: 180,
    maxEn: 180,
    armor: 1400,
    mobility: 85,
    move: 5,
    morale: 100,
    sp: 70,
    maxSp: 70,
    level: 1,
    exp: 0,
    pilot: {
      name: '剛 豪気',
      callsign: 'GOU',
      portrait: '🔥',
      color: '#f87171',
      meleeSkill: 160,
      shootingSkill: 125,
      defenseSkill: 155,
      evadeSkill: 110,
      hitSkill: 145,
      spirits: ['hotBlood', 'guts', 'sureHit', 'ironWall', 'moraleUp'],
      lines: {
        attack: [
          'いっけえぇぇぇ！カイザーの力、見せてやるぜ！',
          '唸れ鋼鉄の拳！粉砕してやる！',
          '逃がしはしねえ！全エネルギー解放だ！',
        ],
        damaged: [
          'くそっ！この程度の装甲の軋み、痛くも痒くもねえ！',
          'まだまだぁ！カイザーは倒れんぞ！',
        ],
        evade: [
          '当たるかよ！巨体だからとナメるな！',
          '甘いぜ！見切った！',
        ],
        destroy: [
          '爆砕せよ！ダイナミック・ノヴァァァッ！！',
          '正義の炎に焼かれて消え失せろ！',
        ],
        win: ['俺たちの勝利だ！鋼鉄の魂に不可能はねえ！'],
      },
    },
    weapons: [
      {
        id: 'k_punch',
        name: 'カイザー・ナックル',
        power: 2800,
        minRange: 1,
        maxRange: 2,
        accuracyMod: 20,
        critMod: 10,
        enCost: 0,
        moraleReq: 100,
        postMove: true,
        type: 'melee',
        description: '超合金の拳をロケット噴射で射出する必中撃。',
        animationKey: 'punch',
      },
      {
        id: 'k_beam',
        name: 'プラズマ・ブラスター',
        power: 3300,
        minRange: 1,
        maxRange: 4,
        accuracyMod: 5,
        critMod: 5,
        enCost: 15,
        moraleReq: 105,
        postMove: false,
        type: 'beam',
        description: '胸部放熱板から放たれる灼熱のプラズマ熱線。',
        animationKey: 'cannon',
      },
      {
        id: 'k_blade',
        name: 'カイザー・ブレード',
        power: 3900,
        minRange: 1,
        maxRange: 1,
        accuracyMod: 15,
        critMod: 20,
        enCost: 20,
        moraleReq: 115,
        postMove: true,
        type: 'melee',
        description: '超重量の灼熱大剣による一刀両断。',
        animationKey: 'slash',
      },
      {
        id: 'k_nova',
        name: 'ダイナミック・ノヴァ',
        power: 5200,
        minRange: 1,
        maxRange: 3,
        accuracyMod: 25,
        critMod: 30,
        enCost: 60,
        moraleReq: 130,
        postMove: true,
        type: 'special',
        description: '全身のリミッターを解除し全火力を叩き込む究極奥義。',
        animationKey: 'nova',
      },
    ],
  },

  arc_weiss: {
    id: 'arc_weiss',
    mechName: 'アーク・ヴァイス',
    faction: 'player',
    icon: '🦅',
    themeColor: '#3b82f6',
    baseHp: 4200,
    baseEn: 200,
    baseArmor: 950,
    baseMobility: 130,
    baseMove: 6,
    upgrades: { hp: 0, en: 0, armor: 0, mobility: 0, weapons: 0 },
    hp: 4200,
    maxHp: 4200,
    en: 200,
    maxEn: 200,
    armor: 950,
    mobility: 130,
    move: 6,
    morale: 100,
    sp: 80,
    maxSp: 80,
    level: 1,
    exp: 0,
    pilot: {
      name: 'レン・クロサキ',
      callsign: 'REN',
      portrait: '🎯',
      color: '#60a5fa',
      meleeSkill: 130,
      shootingSkill: 165,
      defenseSkill: 115,
      evadeSkill: 160,
      hitSkill: 165,
      spirits: ['flash', 'focus', 'accel', 'hotBlood', 'sureHit'],
      lines: {
        attack: [
          'ターゲットロック…照準ブレなし、撃つ！',
          'アーク・ヴァイスの機動力、捉えられるかな？',
          '長距離からの狙撃で沈める！',
        ],
        damaged: [
          'チッ…直撃は免れたがシールドが…！',
          '姿勢制御を急げ！まだやれる！',
        ],
        evade: [
          '遅い！スラスター最大！',
          '予測演算完了…そこだ！',
        ],
        destroy: [
          'メガ粒子収束…目標、消滅を確認！',
          'ミッションコンプリート。次へ移行する。',
        ],
        win: ['敵反応消失。こちらの作戦成功だ。'],
      },
    },
    weapons: [
      {
        id: 'w_vulcan',
        name: 'ヘッド・バルカン',
        power: 2100,
        minRange: 1,
        maxRange: 2,
        accuracyMod: 35,
        critMod: 5,
        enCost: 0,
        moraleReq: 100,
        postMove: true,
        type: 'missile',
        description: '牽制用の高速実弾速射砲。移動後使用可能。',
        animationKey: 'missile',
      },
      {
        id: 'w_saber',
        name: 'プラズマ・サーベル',
        power: 3100,
        minRange: 1,
        maxRange: 1,
        accuracyMod: 20,
        critMod: 25,
        enCost: 10,
        moraleReq: 100,
        postMove: true,
        type: 'melee',
        description: '高エネルギー粒子刃で近接敵を両断する。',
        animationKey: 'slash',
      },
      {
        id: 'w_rifle',
        name: '高収束リニア・ライフル',
        power: 3600,
        minRange: 2,
        maxRange: 5,
        accuracyMod: 25,
        critMod: 15,
        enCost: 15,
        moraleReq: 105,
        postMove: false,
        type: 'beam',
        description: '高初速の電磁ビームによる精密長距離射撃。',
        animationKey: 'rifle',
      },
      {
        id: 'w_cannon',
        name: 'ハイパー・メガ・ランチャー',
        power: 4800,
        minRange: 2,
        maxRange: 6,
        accuracyMod: 15,
        critMod: 20,
        enCost: 45,
        moraleReq: 120,
        postMove: false,
        type: 'beam',
        description: '大型ジェネレーター直結の決戦用超高出力砲。',
        animationKey: 'cannon',
      },
    ],
  },

  cyber_falcon: {
    id: 'cyber_falcon',
    mechName: 'サイバー・ファルコン',
    faction: 'player',
    icon: '⚡',
    themeColor: '#06b6d4',
    baseHp: 3800,
    baseEn: 210,
    baseArmor: 880,
    baseMobility: 145,
    baseMove: 7,
    upgrades: { hp: 0, en: 0, armor: 0, mobility: 0, weapons: 0 },
    hp: 3800,
    maxHp: 3800,
    en: 210,
    maxEn: 210,
    armor: 880,
    mobility: 145,
    move: 7,
    morale: 100,
    sp: 75,
    maxSp: 75,
    level: 1,
    exp: 0,
    pilot: {
      name: 'アイシャ',
      callsign: 'AISHA',
      portrait: '✨',
      color: '#22d3ee',
      meleeSkill: 145,
      shootingSkill: 150,
      defenseSkill: 105,
      evadeSkill: 170,
      hitSkill: 155,
      spirits: ['accel', 'flash', 'focus', 'fortune', 'hotBlood'],
      lines: {
        attack: [
          '音速を超えていくわよ！ついてこられる！？',
          'ファルコン・ブースト点火！一撃で仕留める！',
          '死角から奇襲！逃げ道はないわ！',
        ],
        damaged: [
          'きゃあっ！でもスラスターは生きてる！',
          '当たっちゃった…反撃でお返しよ！',
        ],
        evade: [
          'あはっ、遅いわよ！残像を見てたの？',
          '風のようにすり抜けるわ！',
        ],
        destroy: [
          'ミラージュ・バースト！青き流星の輝きに散りなさい！',
          'ターゲットブレイク！撃墜確認！',
        ],
        win: ['ふぅ、爽快なフライトだったわ！完全勝利！'],
      },
    },
    weapons: [
      {
        id: 'f_gun',
        name: 'ツイン・マシンキャノン',
        power: 2400,
        minRange: 1,
        maxRange: 3,
        accuracyMod: 25,
        critMod: 15,
        enCost: 0,
        moraleReq: 100,
        postMove: true,
        type: 'missile',
        description: '連射性の高い翼端機関砲。',
        animationKey: 'missile',
      },
      {
        id: 'f_cutter',
        name: 'プラズマ・ウィング',
        power: 3200,
        minRange: 1,
        maxRange: 1,
        accuracyMod: 20,
        critMod: 20,
        enCost: 15,
        moraleReq: 105,
        postMove: true,
        type: 'melee',
        description: '音速突撃ですれ違いざまに主翼で切り裂く。',
        animationKey: 'slash',
      },
      {
        id: 'f_missile',
        name: 'ホーミング・マイクロミサイル',
        power: 3500,
        minRange: 2,
        maxRange: 4,
        accuracyMod: 15,
        critMod: 10,
        enCost: 20,
        moraleReq: 110,
        postMove: true,
        type: 'missile',
        description: '無数の誘導弾が敵を包囲して炸裂。',
        animationKey: 'missile',
      },
      {
        id: 'f_mirage',
        name: 'ミラージュ・バースト',
        power: 4900,
        minRange: 1,
        maxRange: 2,
        accuracyMod: 30,
        critMod: 35,
        enCost: 50,
        moraleReq: 125,
        postMove: true,
        type: 'special',
        description: '超音速の分身攻撃で全方位から連続粉砕する必殺技。',
        animationKey: 'nova',
      },
    ],
  },

  angel_wing: {
    id: 'angel_wing',
    mechName: 'エンジェル・ウィング',
    faction: 'player',
    icon: '👼',
    themeColor: '#ec4899',
    baseHp: 4000,
    baseEn: 240,
    baseArmor: 1000,
    baseMobility: 110,
    baseMove: 6,
    upgrades: { hp: 0, en: 0, armor: 0, mobility: 0, weapons: 0 },
    hp: 4000,
    maxHp: 4000,
    en: 240,
    maxEn: 240,
    armor: 1000,
    mobility: 110,
    move: 6,
    morale: 100,
    sp: 90,
    maxSp: 90,
    level: 1,
    exp: 0,
    canRepair: true,
    canResupply: true,
    pilot: {
      name: 'ミナモ',
      callsign: 'MINAMO',
      portrait: '🌸',
      color: '#f472b6',
      meleeSkill: 110,
      shootingSkill: 135,
      defenseSkill: 130,
      evadeSkill: 135,
      hitSkill: 150,
      spirits: ['trust', 'cheer', 'bless', 'flash', 'greatGuts'],
      lines: {
        attack: [
          '皆さんの道を開くため…私も戦います！',
          'ホーリー・アロー、発射！当たって！',
        ],
        damaged: [
          'きゃっ…！まだシールドは持ちます！',
          '大丈夫、後方支援を続けます！',
        ],
        evade: [
          'エンジェルフィールド、展開！防ぎました！',
          '間一髪…！',
        ],
        destroy: [
          '聖なる光よ…安らかに眠ってください。',
          '脅威の排除に成功しました！',
        ],
        win: ['全員無事ですね！本当によかった…！'],
      },
    },
    weapons: [
      {
        id: 'a_arrow',
        name: 'ホーリー・アロー',
        power: 2900,
        minRange: 1,
        maxRange: 4,
        accuracyMod: 30,
        critMod: 10,
        enCost: 10,
        moraleReq: 100,
        postMove: true,
        type: 'beam',
        description: '清らかな光子エネルギーを矢として放つ。',
        animationKey: 'rifle',
      },
      {
        id: 'a_sanctuary',
        name: 'サンクチュアリ・カノン',
        power: 3800,
        minRange: 2,
        maxRange: 5,
        accuracyMod: 20,
        critMod: 15,
        enCost: 35,
        moraleReq: 115,
        postMove: false,
        type: 'special',
        description: '高密度光波を収束させて敵機を消滅させる。',
        animationKey: 'cannon',
      },
    ],
  },
};

// 敵マスター機体テンプレート
export const ENEMY_UNITS_MASTER: Record<string, Omit<Unit, 'x' | 'y' | 'hasMoved' | 'hasActed' | 'activeBuffs'>> = {
  trooper: {
    id: 'trooper',
    mechName: 'ギガント・トルーパー',
    faction: 'enemy',
    icon: '👾',
    themeColor: '#64748b',
    baseHp: 3200,
    baseEn: 120,
    baseArmor: 800,
    baseMobility: 80,
    baseMove: 4,
    upgrades: { hp: 0, en: 0, armor: 0, mobility: 0, weapons: 0 },
    hp: 3200,
    maxHp: 3200,
    en: 120,
    maxEn: 120,
    armor: 800,
    mobility: 80,
    move: 4,
    morale: 100,
    sp: 0,
    maxSp: 0,
    level: 1,
    exp: 0,
    pilot: {
      name: 'カルテル兵',
      callsign: 'SOLDIER',
      portrait: '🪖',
      color: '#94a3b8',
      meleeSkill: 115,
      shootingSkill: 120,
      defenseSkill: 105,
      evadeSkill: 95,
      hitSkill: 120,
      spirits: [],
      lines: {
        attack: ['目標を確認！一斉射撃を開始する！', '死ねぇぇっ！地球のロボットどもめ！'],
        damaged: ['ぐわっ！装甲を貫通された！', 'くそっ、機体制御が乱れる！'],
        evade: ['フン、見え透いた攻撃だ！', '回避成功！'],
        destroy: ['ば、化け物め…脱出…できん…！うわあああっ！'],
        win: ['目標の撃破を確認した。'],
      },
    },
    weapons: [
      {
        id: 't_gun',
        name: 'アサルト・マシンガン',
        power: 2000,
        minRange: 1,
        maxRange: 3,
        accuracyMod: 10,
        critMod: 5,
        enCost: 0,
        moraleReq: 100,
        postMove: true,
        type: 'missile',
        description: '標準的な実弾機関砲。',
        animationKey: 'missile',
      },
      {
        id: 't_blade',
        name: 'ヒート・ダガー',
        power: 2400,
        minRange: 1,
        maxRange: 1,
        accuracyMod: 15,
        critMod: 10,
        enCost: 0,
        moraleReq: 100,
        postMove: true,
        type: 'melee',
        description: '高熱赤熱ブレードによる斬撃。',
        animationKey: 'slash',
      },
    ],
  },

  raider: {
    id: 'raider',
    mechName: 'スカイ・レイダー',
    faction: 'enemy',
    icon: '🦇',
    themeColor: '#a855f7',
    baseHp: 2800,
    baseEn: 140,
    baseArmor: 750,
    baseMobility: 125,
    baseMove: 6,
    upgrades: { hp: 0, en: 0, armor: 0, mobility: 0, weapons: 0 },
    hp: 2800,
    maxHp: 2800,
    en: 140,
    maxEn: 140,
    armor: 750,
    mobility: 125,
    move: 6,
    morale: 100,
    sp: 0,
    maxSp: 0,
    level: 1,
    exp: 0,
    pilot: {
      name: 'レイダー部隊長',
      callsign: 'RAIDER',
      portrait: '🎭',
      color: '#c084fc',
      meleeSkill: 125,
      shootingSkill: 140,
      defenseSkill: 100,
      evadeSkill: 140,
      hitSkill: 145,
      spirits: [],
      lines: {
        attack: ['上空から急降下！ハエのように叩き落としてやる！', '逃げ回っても無駄だ！'],
        damaged: ['なにいっ！？この速度を捉えたというのか！？'],
        evade: ['アハハハ！鈍重な機体め、当たるものか！'],
        destroy: ['ぐああああっ！主翼が折れたぁぁぁっ！'],
        win: ['空の支配者は我らだ！'],
      },
    },
    weapons: [
      {
        id: 'r_laser',
        name: 'ラピッド・レーザー',
        power: 2300,
        minRange: 1,
        maxRange: 3,
        accuracyMod: 20,
        critMod: 10,
        enCost: 10,
        moraleReq: 100,
        postMove: true,
        type: 'beam',
        description: '高周期パルスレーザー。',
        animationKey: 'rifle',
      },
      {
        id: 'r_missile',
        name: 'スプレッド・ボム',
        power: 2700,
        minRange: 1,
        maxRange: 4,
        accuracyMod: 10,
        critMod: 15,
        enCost: 15,
        moraleReq: 105,
        postMove: false,
        type: 'missile',
        description: '上空から広範囲に投下される小型クラスター弾。',
        animationKey: 'missile',
      },
    ],
  },

  goliath: {
    id: 'goliath',
    mechName: 'ヘヴィ・ゴライアス',
    faction: 'enemy',
    icon: '🦏',
    themeColor: '#d97706',
    baseHp: 6000,
    baseEn: 160,
    baseArmor: 1350,
    baseMobility: 70,
    baseMove: 4,
    upgrades: { hp: 0, en: 0, armor: 0, mobility: 0, weapons: 0 },
    hp: 6000,
    maxHp: 6000,
    en: 160,
    maxEn: 160,
    armor: 1350,
    mobility: 70,
    move: 4,
    morale: 100,
    sp: 0,
    maxSp: 0,
    level: 2,
    exp: 0,
    pilot: {
      name: 'ゴライアス操縦士',
      callsign: 'GOLIATH',
      portrait: '🗿',
      color: '#f59e0b',
      meleeSkill: 140,
      shootingSkill: 150,
      defenseSkill: 150,
      evadeSkill: 80,
      hitSkill: 140,
      spirits: [],
      lines: {
        attack: ['主砲発射シークエンス…すべてを吹き飛ばせ！', '装甲の厚さを見せつけてやる！'],
        damaged: ['フン…この重装甲には傷一つつけられん！', 'チイッ、少し響いたか…！'],
        evade: ['フン、かすりもしないわ！'],
        destroy: ['バカな…このゴライアスの装甲を破るだと…！？ドカーン！'],
        win: ['圧倒的な火力と装甲の前には塵も残らん！'],
      },
    },
    weapons: [
      {
        id: 'g_cannon',
        name: '300mmメガキャノン',
        power: 3400,
        minRange: 2,
        maxRange: 5,
        accuracyMod: 10,
        critMod: 10,
        enCost: 15,
        moraleReq: 100,
        postMove: false,
        type: 'beam',
        description: '長砲身から撃ち出される破壊的荷電粒子砲。',
        animationKey: 'cannon',
      },
      {
        id: 'g_crush',
        name: 'アイアン・スマッシュ',
        power: 3000,
        minRange: 1,
        maxRange: 1,
        accuracyMod: 20,
        critMod: 15,
        enCost: 0,
        moraleReq: 100,
        postMove: true,
        type: 'melee',
        description: '巨大な重装甲アームによる圧砕攻撃。',
        animationKey: 'punch',
      },
    ],
  },

  dis_garm: {
    id: 'dis_garm',
    mechName: '暗黒機神ディス・ガルム',
    faction: 'enemy',
    isBoss: true,
    icon: '👿',
    themeColor: '#7c3aed',
    baseHp: 18000,
    baseEn: 300,
    baseArmor: 1500,
    baseMobility: 110,
    baseMove: 5,
    upgrades: { hp: 0, en: 0, armor: 0, mobility: 0, weapons: 0 },
    hp: 18000,
    maxHp: 18000,
    en: 300,
    maxEn: 300,
    armor: 1500,
    mobility: 110,
    move: 5,
    morale: 110,
    sp: 50,
    maxSp: 50,
    level: 3,
    exp: 0,
    pilot: {
      name: 'ガルム司令官',
      callsign: 'GARM',
      portrait: '😈',
      color: '#a78bfa',
      meleeSkill: 170,
      shootingSkill: 165,
      defenseSkill: 160,
      evadeSkill: 135,
      hitSkill: 160,
      spirits: ['ironWall', 'hotBlood'],
      lines: {
        attack: [
          '我がディス・ガルムの刃に散れ！愚かな虫ケラども！',
          '闇の波動を受けよ！貴様らに明日はない！',
        ],
        damaged: [
          'ぐっ…！生意気な小蝿どもが…怒りを買わせたな！',
          '効かぬわ！暗黒障壁の強固さを知れ！',
        ],
        evade: ['ハハハハ！止まって見えるぞ！遅いわ！'],
        destroy: ['おのれえぇぇっ！まだだ…まだネオ・ジェネシス様が…！'],
        win: ['世界は闇に染まるのだ…！'],
      },
    },
    weapons: [
      {
        id: 'dg_scythe',
        name: 'デス・サイズ・スラッシュ',
        power: 3800,
        minRange: 1,
        maxRange: 2,
        accuracyMod: 25,
        critMod: 20,
        enCost: 15,
        moraleReq: 100,
        postMove: true,
        type: 'melee',
        description: '紫電を纏う巨大な死神の大鎌。',
        animationKey: 'slash',
      },
      {
        id: 'dg_shock',
        name: 'ダーク・インフェルノ',
        power: 4500,
        minRange: 1,
        maxRange: 4,
        accuracyMod: 20,
        critMod: 25,
        enCost: 40,
        moraleReq: 115,
        postMove: false,
        type: 'special',
        description: '異次元の暗黒衝撃波を放射して空間ごと粉砕する。',
        animationKey: 'darkness',
      },
    ],
  },

  neo_genesis: {
    id: 'neo_genesis',
    mechName: '終焉使徒ネオ・ジェネシス',
    faction: 'enemy',
    isBoss: true,
    icon: '👑',
    themeColor: '#e11d48',
    baseHp: 32000,
    baseEn: 500,
    baseArmor: 1750,
    baseMobility: 125,
    baseMove: 6,
    upgrades: { hp: 0, en: 0, armor: 0, mobility: 0, weapons: 0 },
    hp: 32000,
    maxHp: 32000,
    en: 500,
    maxEn: 500,
    armor: 1750,
    mobility: 125,
    move: 6,
    morale: 120,
    sp: 100,
    maxSp: 100,
    level: 5,
    exp: 0,
    pilot: {
      name: '創造主 ゼノス',
      callsign: 'XENOS',
      portrait: '👁️',
      color: '#fb7185',
      meleeSkill: 185,
      shootingSkill: 185,
      defenseSkill: 175,
      evadeSkill: 150,
      hitSkill: 180,
      spirits: ['ironWall', 'sureHit', 'hotBlood'],
      lines: {
        attack: [
          'すべては創世の灰燼と化す…これが世界の理だ。',
          '無駄な足掻きをやめよ。終焉を受け入れるがいい。',
          '原初の光よ…この宇宙を無に帰せ！',
        ],
        damaged: [
          'ぬう…この力…人間の意志というものがこれほどとは…！',
          '無意味だ…我は不滅、我が創世は止められぬ！',
        ],
        evade: ['無駄だ。事象はすでに書き換わっている。'],
        destroy: [
          '見事だ…だが…人間の希望の光が…いつまで続くかな……！うわああああっ！',
        ],
        win: ['さあ、新たな世界を始めよう…我の手によって。'],
      },
    },
    weapons: [
      {
        id: 'ng_judgment',
        name: '創世の断罪 (Judgment Light)',
        power: 4400,
        minRange: 1,
        maxRange: 3,
        accuracyMod: 30,
        critMod: 20,
        enCost: 25,
        moraleReq: 105,
        postMove: true,
        type: 'beam',
        description: '全方位に光の柱を召喚し標的を焼き尽くす。',
        animationKey: 'cannon',
      },
      {
        id: 'ng_extinction',
        name: '終焉の黙示録 (Apocalypse Beam)',
        power: 5800,
        minRange: 1,
        maxRange: 5,
        accuracyMod: 25,
        critMod: 35,
        enCost: 65,
        moraleReq: 125,
        postMove: false,
        type: 'special',
        description: '次元の狭間を抉り出し万物を崩壊させる究極の光輪。',
        animationKey: 'darkness',
      },
    ],
  },
};

// ユニット生成ヘルパー
export function createUnitInstance(
  templateId: string,
  faction: 'player' | 'enemy',
  x: number,
  y: number,
  overrides?: Partial<Unit>
): Unit {
  const master = faction === 'player' ? PLAYER_UNITS_MASTER[templateId] : ENEMY_UNITS_MASTER[templateId];
  if (!master) {
    throw new Error(`Unit template not found: ${templateId}`);
  }

  // ディープコピー
  const copy: Unit = {
    ...JSON.parse(JSON.stringify(master)),
    x,
    y,
    hasMoved: false,
    hasActed: false,
    activeBuffs: {},
    ...overrides,
  };

  // 各武器の基礎攻撃力を保持
  copy.weapons.forEach((w) => {
    if (w.basePower === undefined) {
      w.basePower = w.power;
    }
  });

  // 改造値の再計算適用
  applyUpgrades(copy);
  return copy;
}

// 改造ステータス適用
export function applyUpgrades(unit: Unit) {
  const u = unit.upgrades;
  unit.maxHp = unit.baseHp + u.hp * 500;
  unit.maxEn = unit.baseEn + u.en * 20;
  unit.armor = unit.baseArmor + u.armor * 80;
  unit.mobility = unit.baseMobility + u.mobility * 6;
  
  // 武器攻撃力アップ (basePowerを基準に再計算し、重複累積を完全に防止)
  unit.weapons.forEach((w) => {
    if (w.basePower === undefined) {
      w.basePower = w.power;
    }
    w.power = w.basePower + u.weapons * 150;
  });

  // HP/EN上限調整
  if (unit.hp > unit.maxHp) unit.hp = unit.maxHp;
  if (unit.en > unit.maxEn) unit.en = unit.maxEn;
}

// 戦闘計算式
export function calculateCombatForecast(
  attacker: Unit,
  defender: Unit,
  weapon: Weapon,
  _attackerTerrain: TerrainInfo,
  defenderTerrain: TerrainInfo
): {
  hitChance: number;
  estimatedDamage: number;
  critChance: number;
} {
  // 1. 命中率計算
  // 基礎命中率 = 攻撃側照準 + 武器命中補正 - 防御側運動性 + (攻撃側パイロット命中 - 防御側パイロット回避)
  const attackerHitStat = attacker.pilot.hitSkill + (attacker.activeBuffs.focus ? 30 : 0);
  const defenderEvadeStat = defender.pilot.evadeSkill + defender.mobility + (defender.activeBuffs.focus ? 30 : 0) + (defenderTerrain.evadeMod * 100);
  
  let rawHit = attackerHitStat + weapon.accuracyMod - defenderEvadeStat + 100;
  
  if (attacker.activeBuffs.sureHit) rawHit = 100;
  if (defender.activeBuffs.flash) rawHit = 0;
  
  const hitChance = Math.max(0, Math.min(100, Math.round(rawHit)));

  // 2. クリティカル率計算
  let critChance = Math.max(0, Math.min(100, Math.round(weapon.critMod + (attacker.pilot.meleeSkill - defender.pilot.defenseSkill) / 5)));
  if (critChance < 5) critChance = 5;

  // 3. ダメージ計算
  // (攻撃力 * 気力補正 / 100 + パイロットスキル) - (装甲値 * 地形補正)
  const skillFactor = weapon.type === 'melee' ? attacker.pilot.meleeSkill : attacker.pilot.shootingSkill;
  const moraleMult = attacker.morale / 100;
  const attackPower = (weapon.power * moraleMult) + (skillFactor * 10);
  
  const defensePower = (defender.armor * (1 + defenderTerrain.defenseMod)) + (defender.pilot.defenseSkill * 8);
  
  let damage = Math.max(100, Math.round(attackPower - defensePower * 0.7));

  // 熱血
  if (attacker.activeBuffs.hotBlood) {
    damage = Math.round(damage * 2.0);
  }
  // 鉄壁
  if (defender.activeBuffs.ironWall) {
    damage = Math.round(damage * 0.25);
  }

  return {
    hitChance,
    estimatedDamage: damage,
    critChance,
  };
}
