import { OthelloniaPiece } from './types';

export const ALL_PIECES: OthelloniaPiece[] = [
  // ===================== 神属性 (God) =====================
  {
    id: 'god_michael',
    name: 'ミカエル',
    title: '天軍の最高指揮官',
    attribute: 'god',
    rarity: 'S+',
    hp: 2450,
    atk: 1280,
    skill: {
      name: '聖輝・神聖断罪',
      description: 'ひっくり返した枚数×1,400の聖なる特殊ダメージを与える。',
      effectType: 'special_damage',
      condition: { type: 'always' },
      power: 1400,
    },
    comboSkill: {
      name: '天軍の加護',
      description: '自分のHPを2,000回復する。',
      effectType: 'heal',
      condition: { type: 'always' },
      power: 2000,
    },
    iconBg: 'from-amber-400 via-yellow-200 to-amber-500',
    avatarSvg: 'michael',
    flavorText: '「悪しき闇よ、天軍の聖なる剣の前に消え去るがよい！」',
  },
  {
    id: 'god_athena',
    name: 'アテナ',
    title: '英知と勝利の戦神',
    attribute: 'god',
    rarity: 'S+',
    hp: 2600,
    atk: 1220,
    skill: {
      name: 'アイギスの神盾',
      description: '盤面の自分の神属性駒1枚につき1,000の特殊ダメージを与える。',
      effectType: 'special_damage',
      condition: { type: 'always' },
      power: 1000,
    },
    comboSkill: {
      name: 'パルテノンの凱歌',
      description: '通常攻撃力が1.8倍になり、さらにHPを1,200回復する。',
      effectType: 'buff',
      condition: { type: 'always' },
      power: 1.8,
      extraValue: 1200,
    },
    iconBg: 'from-yellow-300 via-amber-200 to-yellow-600',
    avatarSvg: 'athena',
    flavorText: '「知略と勇気こそが、真の勝利をもたらすのです。」',
  },
  {
    id: 'god_jesus',
    name: '救世主メシア',
    title: '奇跡をもたらす光',
    attribute: 'god',
    rarity: 'S',
    hp: 2750,
    atk: 1100,
    skill: {
      name: '大いなる復活の祈り',
      description: '自分の最大HPの20%（約4,000〜5,000）を瞬時に回復する。',
      effectType: 'heal',
      condition: { type: 'always' },
      power: 4500,
    },
    comboSkill: {
      name: '福音の光導',
      description: '自分のHPを2,200回復する。',
      effectType: 'heal',
      condition: { type: 'always' },
      power: 2200,
    },
    iconBg: 'from-emerald-200 via-teal-100 to-sky-300',
    avatarSvg: 'messiah',
    flavorText: '「信じる心があれば、絶望の闇も希望の光に変わります。」',
  },
  {
    id: 'god_valkyrie',
    name: 'ヴァルキリー',
    title: '戦場を駆ける乙女',
    attribute: 'god',
    rarity: 'S',
    hp: 2300,
    atk: 1350,
    skill: {
      name: 'ヴァルハラの天槍',
      description: 'ひっくり返した枚数が2枚以上の時発動。ATKの1.9倍の特殊ダメージを与える。',
      effectType: 'special_damage',
      condition: { type: 'flip_count', minFlips: 2 },
      power: 1.9,
    },
    comboSkill: {
      name: 'エインヘリャルの誇り',
      description: '通常攻撃力が1.7倍になる。',
      effectType: 'buff',
      condition: { type: 'always' },
      power: 1.7,
    },
    iconBg: 'from-sky-300 via-blue-200 to-indigo-400',
    avatarSvg: 'valkyrie',
    flavorText: '「我が槍は主のために！勇猛果敢に敵を討て！」',
  },
  {
    id: 'god_raphael',
    name: 'ラファエル',
    title: '治癒の至高天使',
    attribute: 'god',
    rarity: 'S',
    hp: 2550,
    atk: 1150,
    skill: {
      name: 'セラフィック・グレイス',
      description: '自分のHPを2,800回復する。',
      effectType: 'heal',
      condition: { type: 'always' },
      power: 2800,
    },
    comboSkill: {
      name: '清浄の聖泉',
      description: '自分のHPを1,800回復する。',
      effectType: 'heal',
      condition: { type: 'always' },
      power: 1800,
    },
    iconBg: 'from-teal-300 via-emerald-100 to-cyan-400',
    avatarSvg: 'raphael',
    flavorText: '「傷つきし魂よ、聖なる癒やしの風に包まれなさい。」',
  },
  {
    id: 'god_seraphim',
    name: '熾天使セラフィム',
    title: '六翼の聖天帝',
    attribute: 'god',
    rarity: 'S+',
    hp: 2800,
    atk: 1200,
    skill: {
      name: 'サンクチュアリ・ドーム',
      description: 'HPを2,200回復し、さらに相手に1,800の聖なる特殊ダメージ。',
      effectType: 'special_damage',
      condition: { type: 'always' },
      power: 1800,
      extraValue: 2200,
    },
    comboSkill: {
      name: '熾天の連鎖光波',
      description: '盤面の自駒数×400の特殊ダメージを与え、同量HPを回復。',
      effectType: 'drain',
      condition: { type: 'always' },
      power: 1600,
    },
    leaderSkill: {
      name: '聖なる生命の息吹',
      description: '手駒にある間、毎ターン自分のHPが800回復する。',
      effectType: 'aura_hp_regen',
      power: 800,
    },
    iconBg: 'from-amber-300 via-yellow-100 to-amber-600',
    avatarSvg: 'seraphim',
    flavorText: '「天上の理は不滅。光とともにあり続けんことを。」',
  },
  {
    id: 'god_thor',
    name: 'トール',
    title: '雷霆を轟かす軍神',
    attribute: 'god',
    rarity: 'A',
    hp: 1950,
    atk: 1300,
    skill: {
      name: 'ミョルニル・スマッシュ',
      description: '2枚以上ひっくり返した時発動。1,800の雷撃特殊ダメージ。',
      effectType: 'special_damage',
      condition: { type: 'flip_count', minFlips: 2 },
      power: 1800,
    },
    comboSkill: {
      name: '轟く雷神の咆哮',
      description: '通常攻撃力が1.5倍になる。',
      effectType: 'buff',
      condition: { type: 'always' },
      power: 1.5,
    },
    iconBg: 'from-amber-400 via-yellow-300 to-orange-500',
    avatarSvg: 'thor',
    flavorText: '「雷鎚よ！敵の陣形を粉々に打ち砕いてやれ！」',
  },
  {
    id: 'god_uriel',
    name: 'ウリエル',
    title: '神罰の審問官',
    attribute: 'god',
    rarity: 'A',
    hp: 1900,
    atk: 1250,
    skill: {
      name: '断罪の聖火',
      description: '1,500の特殊ダメージを与える。',
      effectType: 'special_damage',
      condition: { type: 'always' },
      power: 1500,
    },
    comboSkill: {
      name: '聖火の浄化',
      description: 'HPを1,400回復する。',
      effectType: 'heal',
      condition: { type: 'always' },
      power: 1400,
    },
    iconBg: 'from-yellow-400 via-amber-300 to-amber-600',
    avatarSvg: 'uriel',
    flavorText: '「罪深き者に、天罰の鉄槌を。」',
  },
  {
    id: 'god_pegasus',
    name: 'ペガサスナイト',
    title: '白銀の天翔ける翼',
    attribute: 'god',
    rarity: 'A',
    hp: 1850,
    atk: 1200,
    skill: {
      name: '天翔ける聖風',
      description: 'HPを1,600回復する。',
      effectType: 'heal',
      condition: { type: 'always' },
      power: 1600,
    },
    comboSkill: {
      name: '天空の連撃',
      description: '盤面の神駒1枚につき300の特殊ダメージ。',
      effectType: 'special_damage',
      condition: { type: 'always' },
      power: 1200,
    },
    iconBg: 'from-cyan-200 via-sky-100 to-blue-300',
    avatarSvg: 'pegasus',
    flavorText: '「大空を翔け、友を助ける盾となろう！」',
  },
  {
    id: 'god_ra',
    name: '太陽神ラー',
    title: '万物を照らす絶対陽光',
    attribute: 'god',
    rarity: 'S+',
    hp: 2700,
    atk: 1240,
    skill: {
      name: 'ソーラー・プロミネンス',
      description: '相手の現在HPの16%の特殊ダメージを与える（HPが多いほど大打点！）。',
      effectType: 'special_damage',
      condition: { type: 'always' },
      power: 0.16,
    },
    comboSkill: {
      name: '旭日の威光',
      description: '通常攻撃力が1.6倍になり、HPを1,500回復する。',
      effectType: 'buff',
      condition: { type: 'always' },
      power: 1.6,
      extraValue: 1500,
    },
    iconBg: 'from-amber-500 via-orange-300 to-yellow-500',
    avatarSvg: 'ra',
    flavorText: '「我が光は天を覆い、すべての闇を灼き尽くす！」',
  },

  // ===================== 魔属性 (Demon) =====================
  {
    id: 'demon_hades',
    name: '冥王ハーデス',
    title: '幽冥の絶対君主',
    attribute: 'demon',
    rarity: 'S+',
    hp: 2150,
    atk: 1400,
    skill: {
      name: '冥府の略奪',
      description: '相手に2,800の特殊ダメージを与え、自分のHPを2,800吸収回復する。',
      effectType: 'drain',
      condition: { type: 'always' },
      power: 2800,
    },
    comboSkill: {
      name: '死霊の鎖縛',
      description: '相手に毎ターン1,000の毒ダメージを付与する。',
      effectType: 'poison',
      condition: { type: 'always' },
      power: 1000,
    },
    iconBg: 'from-purple-900 via-indigo-900 to-slate-900',
    avatarSvg: 'hades',
    flavorText: '「貴様の魂、冥府の糧として永遠に刻みつけてくれよう。」',
  },
  {
    id: 'demon_lilith',
    name: '夜魔リリス',
    title: '深淵の妖艶なる女王',
    attribute: 'demon',
    rarity: 'S',
    hp: 2050,
    atk: 1320,
    skill: {
      name: 'ナイトメア・ベノム',
      description: '相手に毎ターン1,400の強力な毒ダメージを与える。',
      effectType: 'poison',
      condition: { type: 'always' },
      power: 1400,
    },
    comboSkill: {
      name: '蠱惑の吸血牙',
      description: '相手に1,800のダメージを与え、同量HPを回復する。',
      effectType: 'drain',
      condition: { type: 'always' },
      power: 1800,
    },
    iconBg: 'from-violet-800 via-purple-700 to-fuchsia-900',
    avatarSvg: 'lilith',
    flavorText: '「フフ……甘美な悪夢の中で、静かに朽ち果てなさい。」',
  },
  {
    id: 'demon_clown',
    name: '傀儡師ピエロ',
    title: '狂気のからくり道化',
    attribute: 'demon',
    rarity: 'S',
    hp: 2000,
    atk: 1250,
    skill: {
      name: 'マリオネット・トラップ',
      description: '【罠】このマスが裏返された時、受けたダメージの140%を相手に跳ね返す！',
      effectType: 'trap',
      condition: { type: 'always' },
      power: 1.4,
    },
    comboSkill: {
      name: '狂乱のカーニバル',
      description: '相手に2,000の魔術特殊ダメージを与える。',
      effectType: 'special_damage',
      condition: { type: 'always' },
      power: 2000,
    },
    iconBg: 'from-fuchsia-800 via-purple-900 to-pink-700',
    avatarSvg: 'clown',
    flavorText: '「ヒャッハハ！引っかかったね！ボクの罠は最高だろ？」',
  },
  {
    id: 'demon_reaper',
    name: '死神グリムリーパー',
    title: '魂を刈り取る黒き影',
    attribute: 'demon',
    rarity: 'S+',
    hp: 2200,
    atk: 1450,
    skill: {
      name: 'ソウル・ハーベスト',
      description: '相手の最大HPの18%の特殊ダメージを与える凶悪な一撃！',
      effectType: 'special_damage',
      condition: { type: 'always' },
      power: 0.18,
    },
    comboSkill: {
      name: '黄泉送り',
      description: '相手に2,200のダメージを与え、1,500回復する。',
      effectType: 'drain',
      condition: { type: 'always' },
      power: 2200,
    },
    iconBg: 'from-zinc-900 via-purple-950 to-neutral-900',
    avatarSvg: 'reaper',
    flavorText: '「カチ、コチ……お前の命の砂時計は、これで終わりだ。」',
  },
  {
    id: 'demon_succubus',
    name: 'サキュバス',
    title: '夢魔の愛撫',
    attribute: 'demon',
    rarity: 'A',
    hp: 1850,
    atk: 1280,
    skill: {
      name: 'スウィート・キッス',
      description: '相手に1,500のダメージを与え、同量HPを回復する。',
      effectType: 'drain',
      condition: { type: 'always' },
      power: 1500,
    },
    comboSkill: {
      name: '甘美なる誘惑',
      description: '相手に毎ターン700の毒ダメージを与える。',
      effectType: 'poison',
      condition: { type: 'always' },
      power: 700,
    },
    iconBg: 'from-pink-800 via-rose-900 to-purple-950',
    avatarSvg: 'succubus',
    flavorText: '「ねえ、私にぜんぶ捧げて？痛くしないから……」',
  },
  {
    id: 'demon_paracelsus',
    name: '毒薬師パラケルスス',
    title: '猛毒錬金術の極致',
    attribute: 'demon',
    rarity: 'A',
    hp: 1900,
    atk: 1220,
    skill: {
      name: '腐蝕の劇薬',
      description: '相手に毎ターン1,100の毒ダメージを付与する。',
      effectType: 'poison',
      condition: { type: 'always' },
      power: 1100,
    },
    comboSkill: {
      name: '毒素拡散',
      description: '相手の毒ダメージをさらに500強化する。',
      effectType: 'poison',
      condition: { type: 'always' },
      power: 500,
    },
    iconBg: 'from-emerald-950 via-teal-900 to-purple-950',
    avatarSvg: 'paracelsus',
    flavorText: '「フフ、この紫の液体こそ万物を蝕む至高のエリクサーだ。」',
  },
  {
    id: 'demon_astaroth',
    name: '魔界大公アスタロト',
    title: '深淵なる四十軍団長',
    attribute: 'demon',
    rarity: 'S+',
    hp: 2350,
    atk: 1380,
    skill: {
      name: 'アビス・カタストロフ',
      description: '相手に2,400の魔属性特殊ダメージを与える。',
      effectType: 'special_damage',
      condition: { type: 'always' },
      power: 2400,
    },
    comboSkill: {
      name: '万魔の怨嗟',
      description: '相手に2,000の吸収ダメージ。',
      effectType: 'drain',
      condition: { type: 'always' },
      power: 2000,
    },
    leaderSkill: {
      name: '深淵の腐食支配',
      description: '手駒にある間、相手に与える毒ダメージが1.3倍に強化される。',
      effectType: 'aura_poison_boost',
      power: 1.3,
    },
    iconBg: 'from-violet-950 via-indigo-950 to-purple-900',
    avatarSvg: 'astaroth',
    flavorText: '「混沌こそが世界の真理。深淵へ落ちよ。」',
  },
  {
    id: 'demon_belfegor',
    name: '怠惰のベルフェゴール',
    title: 'まどろみの魔神',
    attribute: 'demon',
    rarity: 'A',
    hp: 1980,
    atk: 1150,
    skill: {
      name: 'まどろみの罠',
      description: '【罠】ひっくり返された時、相手に2,500の固定ダメージを与える！',
      effectType: 'trap',
      condition: { type: 'always' },
      power: 1.2,
      extraValue: 2500,
    },
    comboSkill: {
      name: '重たいあくび',
      description: '相手に1,400の吸収ダメージ。',
      effectType: 'drain',
      condition: { type: 'always' },
      power: 1400,
    },
    iconBg: 'from-indigo-900 via-slate-800 to-purple-950',
    avatarSvg: 'belfegor',
    flavorText: '「ふあぁ……動くの面倒くさい。勝手に自滅してくれない？」',
  },
  {
    id: 'demon_fefnir',
    name: '邪龍ファヴニール',
    title: '黄金を呑みし魔竜',
    attribute: 'demon',
    rarity: 'S',
    hp: 2100,
    atk: 1420,
    skill: {
      name: 'カースド・ブレス',
      description: '盤面の魔駒1枚につき700の特殊ダメージを与える。',
      effectType: 'special_damage',
      condition: { type: 'always' },
      power: 700,
    },
    comboSkill: {
      name: '強欲の顎',
      description: '相手に1,900のダメージを与え、同量回復。',
      effectType: 'drain',
      condition: { type: 'always' },
      power: 1900,
    },
    iconBg: 'from-purple-950 via-rose-950 to-slate-900',
    avatarSvg: 'fefnir',
    flavorText: '「我が財宝に手を伸ばす者に、永遠の呪いを刻もう。」',
  },
  {
    id: 'demon_jack',
    name: 'ジャック・オー・ランタン',
    title: '悪戯な南瓜魔導士',
    attribute: 'demon',
    rarity: 'A',
    hp: 1800,
    atk: 1250,
    skill: {
      name: 'ホラー・トリック',
      description: '相手に毎ターン800の毒と、1,200の特殊ダメージ。',
      effectType: 'special_damage',
      condition: { type: 'always' },
      power: 1200,
      extraValue: 800,
    },
    comboSkill: {
      name: 'トリック・サプライズ',
      description: '相手に1,500の特殊ダメージ。',
      effectType: 'special_damage',
      condition: { type: 'always' },
      power: 1500,
    },
    iconBg: 'from-orange-700 via-purple-900 to-zinc-900',
    avatarSvg: 'jack',
    flavorText: '「トリック・オア・トリート！命か魂か、どっちをくれるんだい？」',
  },

  // ===================== 竜属性 (Dragon) =====================
  {
    id: 'dragon_bahamut',
    name: '真竜皇バハムート',
    title: '空を焦がす終焉の覇竜',
    attribute: 'dragon',
    rarity: 'S+',
    hp: 1750,
    atk: 1780,
    skill: {
      name: '天崩壊・メガフレア',
      description: '【貫通】相手の罠や防御を無視し、通常攻撃力を2.3倍にして焼き尽くす！',
      effectType: 'pierce',
      condition: { type: 'always' },
      power: 2.3,
    },
    comboSkill: {
      name: '極限・ギガフレア',
      description: '【貫通】通常攻撃力が2.1倍になり、敵防御を完全に貫通する。',
      effectType: 'pierce',
      condition: { type: 'always' },
      power: 2.1,
    },
    iconBg: 'from-red-600 via-crimson-700 to-amber-600',
    avatarSvg: 'bahamut',
    flavorText: '「我が咆哮の前に跪け！天地ことごとく灰塵と化せ！」',
  },
  {
    id: 'dragon_liorex',
    name: '紅蓮竜リオレクス',
    title: '爆炎の空の王者',
    attribute: 'dragon',
    rarity: 'S+',
    hp: 1800,
    atk: 1720,
    skill: {
      name: 'インフェルノ・ダイブ',
      description: '2枚以上ひっくり返した時発動。通常攻撃力を2.4倍にする。',
      effectType: 'buff',
      condition: { type: 'flip_count', minFlips: 2 },
      power: 2.4,
    },
    comboSkill: {
      name: '紅蓮の爆炎爪',
      description: '通常攻撃力を1.9倍にする。',
      effectType: 'buff',
      condition: { type: 'always' },
      power: 1.9,
    },
    iconBg: 'from-red-600 via-orange-600 to-rose-700',
    avatarSvg: 'liorex',
    flavorText: '「グオオオッ！紅蓮の業火に巻かれて燃え尽きるがよい！」',
  },
  {
    id: 'dragon_siegfried',
    name: '竜騎士ジークフリート',
    title: '不敗の竜血戦士',
    attribute: 'dragon',
    rarity: 'S',
    hp: 1900,
    atk: 1650,
    skill: {
      name: 'バルムンク・バースト',
      description: '【貫通】通常攻撃力が1.9倍になり、敵の罠を無視して粉砕する。',
      effectType: 'pierce',
      condition: { type: 'always' },
      power: 1.9,
    },
    comboSkill: {
      name: '竜血の覚醒',
      description: '自分のHPが50%以下のとき、通常攻撃力が2.2倍になる！',
      effectType: 'buff',
      condition: { type: 'hp_lte', percent: 50 },
      power: 2.2,
    },
    iconBg: 'from-amber-600 via-red-600 to-yellow-500',
    avatarSvg: 'siegfried',
    flavorText: '「竜の血は我が力！一刀のもとに両断してくれる！」',
  },
  {
    id: 'dragon_volganos',
    name: '雷竜ヴォルガノス',
    title: '青き稲妻の暴君',
    attribute: 'dragon',
    rarity: 'S',
    hp: 1700,
    atk: 1680,
    skill: {
      name: 'プラズマ・カタストロフ',
      description: '通常攻撃力を2.0倍にする電撃の一撃。',
      effectType: 'buff',
      condition: { type: 'always' },
      power: 2.0,
    },
    comboSkill: {
      name: '迅雷連撃',
      description: '通常攻撃力を1.8倍にする。',
      effectType: 'buff',
      condition: { type: 'always' },
      power: 1.8,
    },
    iconBg: 'from-blue-600 via-indigo-600 to-cyan-500',
    avatarSvg: 'volganos',
    flavorText: '「紫電一閃！避ける隙など微塵も与えん！」',
  },
  {
    id: 'dragon_leviathan',
    name: '蒼海竜リヴァイアサン',
    title: '大海原を統べる海竜',
    attribute: 'dragon',
    rarity: 'S',
    hp: 1950,
    atk: 1580,
    skill: {
      name: 'タイダル・テンペスト',
      description: '通常攻撃力を1.9倍にし、さらに1,000の追加ダメージ。',
      effectType: 'buff',
      condition: { type: 'always' },
      power: 1.9,
      extraValue: 1000,
    },
    comboSkill: {
      name: '激流の牙',
      description: '通常攻撃力を1.75倍にする。',
      effectType: 'buff',
      condition: { type: 'always' },
      power: 1.75,
    },
    iconBg: 'from-cyan-600 via-blue-700 to-teal-700',
    avatarSvg: 'leviathan',
    flavorText: '「怒涛の荒波よ、我が敵を海の底へと沈めよ！」',
  },
  {
    id: 'dragon_alduin',
    name: '始祖竜アルドゥイン',
    title: '原初より君臨する古竜',
    attribute: 'dragon',
    rarity: 'S+',
    hp: 1850,
    atk: 1750,
    skill: {
      name: '原初の咆哮',
      description: '【貫通】通常攻撃力を2.1倍にする。',
      effectType: 'pierce',
      condition: { type: 'always' },
      power: 2.1,
    },
    comboSkill: {
      name: '竜帝の剛爪',
      description: '通常攻撃力を2.0倍にする。',
      effectType: 'buff',
      condition: { type: 'always' },
      power: 2.0,
    },
    leaderSkill: {
      name: '竜王の威風堂々',
      description: '手駒にある間、デッキの全竜属性駒のATKが常時1.25倍に強化される！',
      effectType: 'aura_atk',
      power: 1.25,
    },
    iconBg: 'from-amber-700 via-red-800 to-stone-900',
    avatarSvg: 'alduin',
    flavorText: '「古の誓約に従い、力なき者を蹂躙せん。」',
  },
  {
    id: 'dragon_salamander',
    name: '火炎竜サラマンダー',
    title: '溶岩より生まれし焔',
    attribute: 'dragon',
    rarity: 'A',
    hp: 1600,
    atk: 1550,
    skill: {
      name: 'フレイム・バースト',
      description: '通常攻撃力を1.7倍にする。',
      effectType: 'buff',
      condition: { type: 'always' },
      power: 1.7,
    },
    comboSkill: {
      name: '灼熱の牙',
      description: '通常攻撃力を1.6倍にする。',
      effectType: 'buff',
      condition: { type: 'always' },
      power: 1.6,
    },
    iconBg: 'from-orange-600 via-red-600 to-amber-700',
    avatarSvg: 'salamander',
    flavorText: '「燃え盛れ！すべてを溶かす灼熱の炎！」',
  },
  {
    id: 'dragon_lindwurm',
    name: '暴風竜リントヴルム',
    title: '天空の疾風竜',
    attribute: 'dragon',
    rarity: 'A',
    hp: 1650,
    atk: 1520,
    skill: {
      name: 'エアロ・スライサー',
      description: '通常攻撃力を1.65倍にする。',
      effectType: 'buff',
      condition: { type: 'always' },
      power: 1.65,
    },
    comboSkill: {
      name: '旋風裂破',
      description: '通常攻撃力を1.55倍にする。',
      effectType: 'buff',
      condition: { type: 'always' },
      power: 1.55,
    },
    iconBg: 'from-emerald-600 via-teal-600 to-cyan-700',
    avatarSvg: 'lindwurm',
    flavorText: '「疾風より速く、刃より鋭く切り裂かん！」',
  },
  {
    id: 'dragon_brachios',
    name: '地竜ブラキオス',
    title: '大地の巨竜',
    attribute: 'dragon',
    rarity: 'A',
    hp: 1900,
    atk: 1450,
    skill: {
      name: 'アース・クエイク',
      description: '通常攻撃力を1.6倍にする。',
      effectType: 'buff',
      condition: { type: 'always' },
      power: 1.6,
    },
    comboSkill: {
      name: '岩盤崩壊',
      description: '通常攻撃力を1.5倍にする。',
      effectType: 'buff',
      condition: { type: 'always' },
      power: 1.5,
    },
    iconBg: 'from-stone-600 via-amber-800 to-stone-800',
    avatarSvg: 'brachios',
    flavorText: '「大地を踏み鳴らせ！その震撼に恐れおののけ！」',
  },
  {
    id: 'dragon_baby',
    name: 'ベビードラゴン',
    title: '未来の覇竜',
    attribute: 'dragon',
    rarity: 'A',
    hp: 1550,
    atk: 1480,
    skill: {
      name: 'プチ・ファイア',
      description: '通常攻撃力を1.55倍にする。',
      effectType: 'buff',
      condition: { type: 'always' },
      power: 1.55,
    },
    comboSkill: {
      name: 'ドラゴンの絆',
      description: '通常攻撃力を1.6倍にする。',
      effectType: 'buff',
      condition: { type: 'always' },
      power: 1.6,
    },
    iconBg: 'from-rose-500 via-orange-400 to-amber-500',
    avatarSvg: 'babydragon',
    flavorText: '「がおーっ！ボクだって大きくなったら強いんだぞ！」',
  },
];

// 駒IDマップ
export const PIECES_MAP: Record<string, OthelloniaPiece> = ALL_PIECES.reduce(
  (acc, piece) => {
    acc[piece.id] = piece;
    return acc;
  },
  {} as Record<string, OthelloniaPiece>
);

// テンプレプリセットデッキ (10枚デッキ: リーダー + 9枚)
export const PRESET_DECKS: {
  id: string;
  name: string;
  description: string;
  attribute: 'god' | 'demon' | 'dragon' | 'mixed';
  leaderId: string;
  pieceIds: string[];
}[] = [
  {
    id: 'preset_dragon_burst',
    name: '烈火の竜皇速攻デッキ',
    description: '始祖竜アルドゥインのオーラATKバフと真竜皇バハムートの貫通で一気に削り切る超攻撃デッキ！',
    attribute: 'dragon',
    leaderId: 'dragon_alduin',
    pieceIds: [
      'dragon_alduin',
      'dragon_bahamut',
      'dragon_liorex',
      'dragon_siegfried',
      'dragon_volganos',
      'dragon_leviathan',
      'dragon_salamander',
      'dragon_lindwurm',
      'dragon_brachios',
      'dragon_baby',
    ],
  },
  {
    id: 'preset_god_heal',
    name: '聖天の光輝耐久デッキ',
    description: '熾天使セラフィムの毎ターン回復とジーザス・ラファエルの超回復、ミカエル＆ラーの割合特殊ダメージで確実に追い詰める神デッキ！',
    attribute: 'god',
    leaderId: 'god_seraphim',
    pieceIds: [
      'god_seraphim',
      'god_michael',
      'god_athena',
      'god_jesus',
      'god_valkyrie',
      'god_raphael',
      'god_thor',
      'god_uriel',
      'god_pegasus',
      'god_ra',
    ],
  },
  {
    id: 'preset_demon_poison',
    name: '冥府の毒罠カースデッキ',
    description: 'アスタロトの毒オーラ、リリスの猛毒、ハーデスの吸収、ピエロ・ベルフェゴールの罠で相手の反撃を封じるテクニカル魔デッキ！',
    attribute: 'demon',
    leaderId: 'demon_astaroth',
    pieceIds: [
      'demon_astaroth',
      'demon_hades',
      'demon_lilith',
      'demon_clown',
      'demon_reaper',
      'demon_succubus',
      'demon_paracelsus',
      'demon_belfegor',
      'demon_fefnir',
      'demon_jack',
    ],
  },
  {
    id: 'preset_mixed_legend',
    name: '三界統一・レジェンド混合デッキ',
    description: '神の回復力、魔の搦め手、竜の突破力を兼ね備えた柔軟な万能ハイブリッドデッキ！',
    attribute: 'mixed',
    leaderId: 'god_seraphim',
    pieceIds: [
      'god_seraphim',
      'god_michael',
      'god_jesus',
      'demon_hades',
      'demon_lilith',
      'demon_clown',
      'dragon_bahamut',
      'dragon_liorex',
      'dragon_siegfried',
      'dragon_volganos',
    ],
  },
];
