import { StageInfo } from './types';
import { PIECES_MAP } from './piecesData';

export const STAGES: StageInfo[] = [
  {
    id: 1,
    name: '第1話：初陣！見習い騎士の道標',
    subtitle: '竜の咆哮が響く修練の広場',
    bossName: '見習い竜騎士レオ',
    bossTitle: '未来を夢見る若き竜騎士',
    bossAttribute: 'dragon',
    bossHp: 16000,
    bossLeader: PIECES_MAP['dragon_baby'],
    bossDeck: [
      PIECES_MAP['dragon_baby'],
      PIECES_MAP['dragon_salamander'],
      PIECES_MAP['dragon_lindwurm'],
      PIECES_MAP['dragon_brachios'],
      PIECES_MAP['dragon_volganos'],
      PIECES_MAP['god_thor'],
      PIECES_MAP['demon_jack'],
      PIECES_MAP['dragon_salamander'],
      PIECES_MAP['dragon_lindwurm'],
      PIECES_MAP['dragon_baby'],
    ],
    description: 'まずは基本の挟み反転とスキル発動を体験しよう！角マスを狙って有利に進めよう。',
    storyDialog: '「手加減なしで行くよ！僕とベビードラゴンのコンビネーション、受けてみて！」',
    rewardExp: 100,
    gimmicks: [
      { x: 0, y: 0, gimmick: 'buff' },
      { x: 5, y: 5, gimmick: 'buff' },
    ],
    starConditions: ['クエストをクリアする', '残HP50%以上で勝利', '12ターン以内に勝利'],
  },
  {
    id: 2,
    name: '第2話：聖林の試練！天翔けるペガサス',
    subtitle: '神聖なる木漏れ日の回廊',
    bossName: '聖導師カレン',
    bossTitle: '天馬を駆る聖なる乙女',
    bossAttribute: 'god',
    bossHp: 19000,
    bossLeader: PIECES_MAP['god_pegasus'],
    bossDeck: [
      PIECES_MAP['god_pegasus'],
      PIECES_MAP['god_uriel'],
      PIECES_MAP['god_thor'],
      PIECES_MAP['god_raphael'],
      PIECES_MAP['god_athena'],
      PIECES_MAP['god_michael'],
      PIECES_MAP['god_uriel'],
      PIECES_MAP['god_raphael'],
      PIECES_MAP['god_pegasus'],
      PIECES_MAP['god_thor'],
    ],
    description: '相手は高いHPと回復スキルを多用してくるぞ。竜の高火力や魔の毒で削り切ろう！',
    storyDialog: '「迷い込んできた旅人よ。聖林の祝福をその身に受ける覚悟はあるかしら？」',
    rewardExp: 200,
    gimmicks: [
      { x: 0, y: 5, gimmick: 'heal' },
      { x: 5, y: 0, gimmick: 'heal' },
    ],
    starConditions: ['クエストをクリアする', '残HP60%以上で勝利', '10ターン以内に勝利'],
  },
  {
    id: 3,
    name: '第3話：宵闇の迷宮！毒薬師と怪奇の人形',
    subtitle: '霧深き毒沼の古城',
    bossName: '道化師マリオット',
    bossTitle: '毒と罠を弄ぶ傀儡師',
    bossAttribute: 'demon',
    bossHp: 18500,
    bossLeader: PIECES_MAP['demon_clown'],
    bossDeck: [
      PIECES_MAP['demon_clown'],
      PIECES_MAP['demon_paracelsus'],
      PIECES_MAP['demon_succubus'],
      PIECES_MAP['demon_belfegor'],
      PIECES_MAP['demon_jack'],
      PIECES_MAP['demon_lilith'],
      PIECES_MAP['demon_paracelsus'],
      PIECES_MAP['demon_succubus'],
      PIECES_MAP['demon_belfegor'],
      PIECES_MAP['demon_clown'],
    ],
    description: 'ピエロの罠駒を裏返すとカウンターダメージを受けるぞ！貫通スキルで無視するか慎重に立ち回れ！',
    storyDialog: '「ケケケッ！どこに罠があるかわかるかな〜？うっかり踏んだら痛いよ〜！」',
    rewardExp: 350,
    gimmicks: [
      { x: 1, y: 1, gimmick: 'damage' },
      { x: 4, y: 4, gimmick: 'damage' },
    ],
    starConditions: ['クエストをクリアする', '敵の毒ダメージを耐えて勝利', '残HP40%以上で勝利'],
  },
  {
    id: 4,
    name: '第4話：紅蓮の咆哮！空の王者リオレクス',
    subtitle: '灼熱の活火山マグマベース',
    bossName: '竜将軍ヴァルザード',
    bossTitle: '灼熱の炎を統べる剛腕',
    bossAttribute: 'dragon',
    bossHp: 21000,
    bossLeader: PIECES_MAP['dragon_liorex'],
    bossDeck: [
      PIECES_MAP['dragon_liorex'],
      PIECES_MAP['dragon_siegfried'],
      PIECES_MAP['dragon_volganos'],
      PIECES_MAP['dragon_salamander'],
      PIECES_MAP['dragon_lindwurm'],
      PIECES_MAP['dragon_brachios'],
      PIECES_MAP['dragon_volganos'],
      PIECES_MAP['dragon_siegfried'],
      PIECES_MAP['dragon_liorex'],
      PIECES_MAP['dragon_salamander'],
    ],
    description: 'リオレクスの強烈な攻撃バフに注意！コンボ導線を作らせないように石を配置しよう。',
    storyDialog: '「我が業火に焼かれて消し炭となるか、それとも打ち破ってみせるか！いざ勝負！」',
    rewardExp: 500,
    gimmicks: [
      { x: 0, y: 0, gimmick: 'buff' },
      { x: 5, y: 5, gimmick: 'buff' },
      { x: 0, y: 5, gimmick: 'buff' },
      { x: 5, y: 0, gimmick: 'buff' },
    ],
    starConditions: ['クエストをクリアする', '相手に1回で5,000以上の大打点を与える', '残HP50%以上で勝利'],
  },
  {
    id: 5,
    name: '第5話：神威顕現！戦乙女のヴァルハラ',
    subtitle: '天空にそびえる黄金の神殿',
    bossName: '戦乙女ヴァルキリー',
    bossTitle: '主神に捧げる無双の戦姫',
    bossAttribute: 'god',
    bossHp: 23000,
    bossLeader: PIECES_MAP['god_athena'],
    bossDeck: [
      PIECES_MAP['god_athena'],
      PIECES_MAP['god_valkyrie'],
      PIECES_MAP['god_michael'],
      PIECES_MAP['god_jesus'],
      PIECES_MAP['god_raphael'],
      PIECES_MAP['god_thor'],
      PIECES_MAP['god_ra'],
      PIECES_MAP['god_valkyrie'],
      PIECES_MAP['god_michael'],
      PIECES_MAP['god_athena'],
    ],
    description: 'アテナとヴァルキリーの連携コンボは絶大！神駒を盤面に溜めさせないよう盤面を制圧せよ。',
    storyDialog: '「神々の領域に足を踏み入れた勇士よ。我が神槍の一撃、受けて立たれよ！」',
    rewardExp: 700,
    gimmicks: [
      { x: 2, y: 1, gimmick: 'heal' },
      { x: 3, y: 4, gimmick: 'heal' },
    ],
    starConditions: ['クエストをクリアする', '残HP50%以上で勝利', '8ターン以内に勝利'],
  },
  {
    id: 6,
    name: '第6話：冥府の黄泉戸！夜魔リリスと死神',
    subtitle: '魂が彷徨う奈落の門',
    bossName: '夜魔リリス',
    bossTitle: '深淵の妖艶なる女王',
    bossAttribute: 'demon',
    bossHp: 24000,
    bossLeader: PIECES_MAP['demon_astaroth'],
    bossDeck: [
      PIECES_MAP['demon_astaroth'],
      PIECES_MAP['demon_lilith'],
      PIECES_MAP['demon_reaper'],
      PIECES_MAP['demon_hades'],
      PIECES_MAP['demon_fefnir'],
      PIECES_MAP['demon_clown'],
      PIECES_MAP['demon_paracelsus'],
      PIECES_MAP['demon_reaper'],
      PIECES_MAP['demon_lilith'],
      PIECES_MAP['demon_hades'],
    ],
    description: '毎ターン毒ダメージが重なり、リリスと死神の吸収攻撃でジリジリ追い詰められるぞ！',
    storyDialog: '「うふふ……あなたの魂の鼓動、とても美味しそうね。ぜんぶ頂戴……？」',
    rewardExp: 900,
    gimmicks: [
      { x: 1, y: 4, gimmick: 'damage' },
      { x: 4, y: 1, gimmick: 'damage' },
    ],
    starConditions: ['クエストをクリアする', '残HP40%以上で勝利', '1度で6,000以上の大打点を出す'],
  },
  {
    id: 7,
    name: '第7話：光翼の審判！熾天使セラフィム',
    subtitle: '全知全能の光が集う天上界の頂',
    bossName: '熾天使セラフィム',
    bossTitle: '六翼の聖天帝',
    bossAttribute: 'god',
    bossHp: 27000,
    bossLeader: PIECES_MAP['god_seraphim'],
    bossDeck: [
      PIECES_MAP['god_seraphim'],
      PIECES_MAP['god_michael'],
      PIECES_MAP['god_athena'],
      PIECES_MAP['god_jesus'],
      PIECES_MAP['god_ra'],
      PIECES_MAP['god_raphael'],
      PIECES_MAP['god_valkyrie'],
      PIECES_MAP['god_thor'],
      PIECES_MAP['god_michael'],
      PIECES_MAP['god_seraphim'],
    ],
    description: 'リーダーオーラで毎ターンHPが800自動回復！圧倒的な回復量を超える瞬間最大火力を叩き込め！',
    storyDialog: '「聖なる理は絶対なり。汝の運命の天秤、ここで定めよう！」',
    rewardExp: 1200,
    gimmicks: [
      { x: 0, y: 0, gimmick: 'heal' },
      { x: 5, y: 5, gimmick: 'heal' },
      { x: 0, y: 5, gimmick: 'buff' },
      { x: 5, y: 0, gimmick: 'buff' },
    ],
    starConditions: ['クエストをクリアする', '残HP50%以上で勝利', '10ターン以内に勝利'],
  },
  {
    id: 8,
    name: '最終話：終焉と創世！真竜皇バハムート',
    subtitle: '天地鳴動！混沌の最終決戦',
    bossName: '真竜皇バハムート',
    bossTitle: '空を焦がす終焉の覇竜',
    bossAttribute: 'dragon',
    bossHp: 30000,
    bossLeader: PIECES_MAP['dragon_alduin'],
    bossDeck: [
      PIECES_MAP['dragon_alduin'],
      PIECES_MAP['dragon_bahamut'],
      PIECES_MAP['dragon_liorex'],
      PIECES_MAP['dragon_siegfried'],
      PIECES_MAP['dragon_volganos'],
      PIECES_MAP['dragon_leviathan'],
      PIECES_MAP['dragon_bahamut'],
      PIECES_MAP['dragon_liorex'],
      PIECES_MAP['dragon_siegfried'],
      PIECES_MAP['dragon_alduin'],
    ],
    description: '究極の竜皇デッキ！超高火力の貫通メガフレアと爆発的コンボが襲いかかる！逆転の一手を決めろ！',
    storyDialog: '「我こそは世界の終焉であり創世なり！その魂の限界、今ここで見せてみよッッ！！」',
    rewardExp: 2000,
    gimmicks: [
      { x: 1, y: 1, gimmick: 'buff' },
      { x: 4, y: 4, gimmick: 'buff' },
      { x: 1, y: 4, gimmick: 'buff' },
      { x: 4, y: 1, gimmick: 'buff' },
    ],
    starConditions: ['真竜皇バハムートを討伐する', '残HP30%以上で勝利', '1手で8,000以上の逆転大打点を出す'],
  },
];
